SELECT * FROM HR.EMPLOYEES;

--유저 목록
SELECT * FROM ALL_USERS;
--유저 권한 확인
SELECT * FROM USER_SYS_PRIVS;

--계정생성
CREATE USER USER01 IDENTIFIED BY USER01; --ID: USER01, PW: USER01

--권한부여 (접속권한, 테이블 뷰 시퀀스 프로시저 생성권한)
GRANT CREATE SESSION, CREATE TABLE, CREATE SEQUENCE, CREATE VIEW, CREATE PROCEDURE TO USER01; -- USER01 한테 부여

--테이블 스페이스(데이터를 저장하는 물리적인 공간) 지정
ALTER USER USER01 DEFAULT TABLESPACE USERS QUOTA UNLIMITED ON USERS; --테이블을 생성하기 위해 테이블 스페이스 생성 필요
--(수정한다 유저01 기본 테이블 스페이스는 USERS이고, 무제한을 사용한다 ON USERS테이블 스페이스를)

--권한 회수
REVOKE CREATE SESSION FROM USER01; --접속권한 뺏음

--계정 삭제 
DROP USER USER01;
-----------------------------------------------------------------
--롤(ROLE) -권한의 그룹을 통한 권한부여
CREATE USER USER01 IDENTIFIED BY USER01;

GRANT CONNECT, RESOURCE TO USER01; --CONNECT접속롤, RESOURCE개발롤, DBA 관리자 롤

ALTER USER USER01 DEFAULT TABLESPACE USERS QUOTA UNLIMITED ON USERS;












