CREATE TABLE MEMBER (
    ID VARCHAR2(30) PRIMARY KEY,
    PW VARCHAR2(30),
    AGE NUMBER(30),
    EMAIL VARCHAR2(30)
    );
    
    INSERT INTO 테이블명(컬럼명) VALUES (값, 값, 값, 값);
    
    SELECT * FROM MEMBER;
    INSERT INTO MEMBER VALUES ('AAA', 'AAA', 10, 'AAA');
    INSERT INTO MEMBER VALUES ('BBB', 'BBB', 10, 'BBB');
    INSERT INTO MEMBER VALUES ('CCC', 'CCC', 10, 'CCC');
    INSERT INTO MEMBER VALUES ('DDD', 'DDD', 10, 'DDD');
    
    SELECT * FROM MEMBER WHERE AGE >= 10; 
     
    SELECT * FROM EMPLOYEES;
    SELECT * FROM DEPARTMENTS;
     
     
     SELECT E.EMPLOYEE_ID, 
            E.JOB_ID, 
            D.DEPARTMENT_NAME, 
            E.FIRST_NAME 
     FROM EMPLOYEES E 
     LEFT JOIN DEPARTMENTS D
     ON E.DEPARTMENT_ID = D.DEPARTMENT_ID
     WHERE EMPLOYEE_ID = 101;
          
     