CREATE TABLE BOARD (
    BNO NUMBER(10),                 -- 글번호 PK
    WRITER VARCHAR2(30) NOT NULL,   -- 회원테이블과 연관되는 FK
    TITLE VARCHAR2(200) NOT NULL,   -- 작성자
    CONTENT VARCHAR2(500),          -- 내용/ 한글은 250자까지 / 
    REGDATE DATE DEFAULT SYSDATE,   -- 등록일
    HIT NUMBER(5) DEFAULT(0)        -- 조회수

);
ALTER TABLE BOARD ADD CONSTRAINT BOARD_BNO_PK PRIMARY KEY (BNO);

CREATE SEQUENCE BOARD_SEQ NOCACHE;

SELECT * FROM BOARD ORDER BY BNO DESC;

UPDATE BOARD SET HIT = HIT+1 WHERE BNO =?;

DELETE  FROM BOARD WHERE BNO = 3;